name: "Build & Release iOS"

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build & Release iOS 🍎
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3